### ISSUE TITLE
為什麼不自己抓 root.path 下的子目錄

### ISSUE THREAD

**Issue by ybon3** [MontyPan/DocCenter#1]
As title，還要靠 `repo.list` 來決定列出的 item？

我建議系統自己掃描 `root.path` 下的子目錄，如果該目錄含有 `docs` 的子目錄就列為清單中的 item。

**Comment by MontyPan** [comment]
~答：因為作者高興~ 😈  

如果只看目前能提供的功能，你的想法（或許）是合理的。但是 DocCenter 的目標是自動 sync repo，所以自動掃描 `root.path` 下的 folder 並沒有什麼意義。終究還是要設定 repo 的 URL、帳號密碼之類的才能動作。

至於什麼時候會有自動 sync repo，那又是另一個故事了 [遠目]
